[package]
name = "qitoy-link_cut_tree"
version.workspace = true
edition.workspace = true

[[example]]
name = "lca"
path = "examples/lca.rs"

[dependencies]
proconio.workspace = true
itertools.workspace = true
