[package]
name = "qitoy-dfa"
version.workspace = true
edition.workspace = true

[[example]]
name = "xor_sum"
path = "examples/xor_sum.rs"

[dependencies]
ac-library-rs.workspace = true

[dev-dependencies]
proconio.workspace = true
qitoy-nfa.path = "../nfa"
qitoy-dfa-leq_inv.path = "../leq_inv"
